Fix usage of depreciated ReflectionType::__toString()
PHPUnit throws deprecation errors when Phake uses this method

ErrorException: Function ReflectionType::__toString() is deprecated